# Generated by Django 5.0.6 on 2024-06-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
